### ISSUE TITLE
建议：页下双链学一下 Logseq 的做法

### ISSUE THREAD

**Issue by hdg8087** [IAliceBobI/sy-tomato-plugin#10]
目前的页下双链，感觉信息挺多，有点乱。
可以学一下Logseq或者wolai或者obsidian的做法。
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/71086865/9694063a-5915-433b-8104-7e6afaf3dd85)

**Comment by IAliceBobI** [comment]
@hdg8087 感谢反馈。我其实也想做好，只是我前端技术比较菜，这样已经是极限。等我有空了，再优化美化一下。再次感谢！

**Comment by uulaile** [comment]
确实有点乱,难以下手

**Comment by IAliceBobI** [comment]
@uulaile 目前新版本有大量更新。欢迎试试。基于新版本，有新的想法，欢迎提出。

**Comment by IAliceBobI** [comment]
@hdg8087 目前新版本有大量更新。欢迎试试。基于新版本，有新的想法，欢迎开新的 issue 提出。
