### ISSUE TITLE
虚拟引用转引用

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#11]
导入markdown文件时没有双链，但是虚拟引用可以找到，如果能把当前文档的虚拟引用转化成引用，就可以一键构建双链关系。 quicker动作的参考。
https://getquicker.net/Sharedaction?code=6172a937-b860-4f87-a410-08dbf16456ca

**Comment by IAliceBobI** [comment]
感谢建议。不错的想法。我先想想。

**Comment by AvoidantPerDis** [comment]
可以默认选择同母文档下文档啥的，不然会误引用

**Comment by IAliceBobI** [comment]
要搞的话，也是匹配到哪个就用哪个。方便知识的关联。

**Comment by AvoidantPerDis** [comment]
合理

**Comment by IAliceBobI** [comment]
@AvoidantPerDis 我觉得不需要转 ， 直接打开就好了。


![image](https://github.com/user-attachments/assets/79f92df4-5eb1-4d30-85a4-6d53d15fb31f)

**Comment by IAliceBobI** [comment]
默认快捷键是 alt + shift +a

**Comment by AvoidantPerDis** [comment]
ok
