### ISSUE TITLE
文档链接转文本

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#12]
直接从网页复制markdown文件粘贴的话会存在大量的链接文本，希望能有个功能，能把当前文档的链接全部转化为文本。可以的话子文档也一键转换更好。

**Comment by IAliceBobI** [comment]
感谢建议，我找个空闲时间看看。

**Comment by AvoidantPerDis** [comment]
我自己是用正则的
\[(.*?)\]\((?!.*?\.(?:png|jpe?g|gif|webp))https?:\/\/[^\)]+\)替换$1
这样保留图片

**Comment by IAliceBobI** [comment]
> 直接从网页复制markdown文件粘贴的话会存在大量的链接文本，希望能有个功能，能把当前文档的链接全部转化为文本。可以的话子文档也一键转换更好。

有没有例子看看？用的人多吗？

**Comment by AvoidantPerDis** [comment]
估计用的人不多，我也不怎么用了

**Comment by AvoidantPerDis** [comment]
https://publish.obsidian.md/wanyulawyer/Lawsight

**Comment by IAliceBobI** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/3294007/a3f9cb06-3a86-4b02-813e-444c66e2639e)
你说把链接去掉？

**Comment by AvoidantPerDis** [comment]
就是变成纯文本

**Comment by IAliceBobI** [comment]
感觉没太大用处，我都没这么用过。复制后，到思源， ctrl shift v 就可以了。

```
民法典及配套司法解释
中华人民共和国民法典
最高人民法院关于适用《中华人民共和国民法典》时间效力的若干规定
最高人民法院关于适用《中华人民共和国民法典》物权编的解释（一）
最高人民法院关于适用《中华人民共和国民法典》合同编通则若干问题的解释
最高人民法院关于适用《中华人民共和国民法典》有关担保制度的解释
最高人民法院关于适用《中华人民共和国民法典》婚姻家庭编的解释（一）
最高人民法院关于适用《中华人民共和国民法典》继承编的解释（一）
全国法院贯彻实施民法典工作会议纪要
最高人民法院关于审理城镇房屋租赁合同纠纷案件具体应用法律若干问题的解释（2020修正）
最高人民法院关于确定民事侵权精神损害赔偿责任若干问题的解释（2020修正）
最高人民法院关于审理不正当竞争民事案件应用法律若干问题的解释
最高人民法院关于审理道路交通事故损害赔偿案件适用法律若干问题的解释（2020修正）
最高人民法院关于审理独立保函纠纷案件若干问题的规定
最高人民法院关于审理环境民事公益诉讼案件适用法律若干问题的解释（2020修正）
```
