### ISSUE TITLE
临时关闭文档的闪卡

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#13]
虽然直接放到关闭笔记本也能达到关闭闪卡的效果，但是对应文档的引用的话会消失。
结合闪卡优先级设置个-1优先级什么的，就可以达到屏蔽的效果然后恢复的话就全部恢复成50

**Comment by AvoidantPerDis** [comment]
还有就是删除文档的所有显卡，现在要一个一个手点。考虑这个操作的使用频率和危险性，可以加个多次确认。

**Comment by IAliceBobI** [comment]
要删除文档内全部闪卡，有个闪卡增强插件可以做。

目前删除闪卡就一次确认。多次确认会造成不必要的麻烦。

**Comment by AvoidantPerDis** [comment]
那个增强插件删除的是一页的闪卡，我没找到删除全部的办法

**Comment by IAliceBobI** [comment]
@AvoidantPerDis 你是说对于长文档，他只是删除当前加载的内容里面的闪卡吗？

**Comment by AvoidantPerDis** [comment]
对，我测过

**Comment by IAliceBobI** [comment]
> 虽然直接放到关闭笔记本也能达到关闭闪卡的效果，但是对应文档的引用的话会消失。 结合闪卡优先级设置个-1优先级什么的，就可以达到屏蔽的效果然后恢复的话就全部恢复成50

最小是0，不是-1。

**Comment by AvoidantPerDis** [comment]
不过既然能实现，应该就有办法

**Comment by AvoidantPerDis** [comment]
都行，有效果就行

**Comment by IAliceBobI** [comment]
你要会编程可以快速做个。删除当前页的闪卡。

**Comment by AvoidantPerDis** [comment]
还不如用连点器手点管理界面的删除

**Comment by IAliceBobI** [comment]
也行。不过我还是说一下思路。找个sqlite 数据库查看的工具 ，打开  SiYuan/temp/siyuan.db    。

可以从表 attributes 里查到 custom-riff-decks 属性。可以看到是哪个文档的，以及闪卡的块id。 然后调用`"/api/riff/removeRiffCards"` 接口，传入块id就可以了。

**Comment by AvoidantPerDis** [comment]
感谢分享

**Comment by IAliceBobI** [comment]
@AvoidantPerDis  支持了：https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.16.2

**Comment by AvoidantPerDis** [comment]
神速啊，佬

**Comment by AvoidantPerDis** [comment]
@IAliceBobI 佬，我发现我没考虑好，全部设成0可以达到暂停的效果，但是会覆盖掉原先的优先级。这个功能目前够用了，可以等官方或者有什么其他更好办法

**Comment by AvoidantPerDis** [comment]
确实很方便，不过速度好像有点慢 我300个闪卡，卡了几十秒

**Comment by IAliceBobI** [comment]
@AvoidantPerDis 要查db。已经是同时发请求了。新版思源没这么慢吧。
