### ISSUE TITLE
调整嵌入块内部闪卡优先级时不弹窗

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#14]
不知道这个能不能实现。

**Comment by IAliceBobI** [comment]
是说界面闪烁一下吗？这个我都没明白什么原理。我应该修复不了。

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/718850ca-92e4-4bf8-9bf9-c28703905158)
这样

**Comment by IAliceBobI** [comment]
因为你点中了面包屑。这个是思源本身的特性。

你把窗口拉宽点，就是闪烁一下。可以接受。

**Comment by AvoidantPerDis** [comment]
ok

**Comment by IAliceBobI** [comment]
@AvoidantPerDis 不弹窗了。
