### ISSUE TITLE
刷新虚拟引用,可以增加一个快捷键吗？

### ISSUE THREAD

**Issue by uulaile** [IAliceBobI/sy-tomato-plugin#15]
因为用的比较频繁,所以想有一个快捷键

**Comment by IAliceBobI** [comment]
> 因为用的比较频繁,所以想有一个快捷键

https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.15.15  可以下载了。

**Comment by IAliceBobI** [comment]
@uulaile 需要自己设置快捷键。
