### ISSUE TITLE
现在反向链接好看多了,但还有几个问题

### ISSUE THREAD

**Issue by uulaile** [IAliceBobI/sy-tomato-plugin#16]
1.反向链接里面的内容不能直接编辑保存。
2.反向链接没有创建日期排序
3.“移动到文档”,应该有确认键,不小心按错,原文哪里切出来都不知道了。
大佬考虑一下,谢谢！

**Comment by uulaile** [comment]
选择文字后,快捷编辑栏,也不会弹出。

**Comment by IAliceBobI** [comment]
做的时候没考虑编辑，后续考虑编辑。
没有确认，主要是为了快速整理。熟练了还是不用确认方便。
按照日期排序，我看看怎么搞。
多谢反馈。

**Comment by uulaile** [comment]
按照daily note的流程来看,反链排序,按照创建日期来的话,看着顺溜一些,也不用动脑,从头往下看就好了。当然最好是有个开关自己选。

**Comment by IAliceBobI** [comment]
我先试试能不能支持编辑。

**Comment by IAliceBobI** [comment]
@uulaile 目前已经可编辑，拖拽。

**Comment by uulaile** [comment]
还可以更进一步,不用浮窗就能直接更改。

**Comment by IAliceBobI** [comment]
> 还可以更进一步,不用浮窗就能直接更改。

可以的，你试试。

**Comment by IAliceBobI** [comment]
@uulaile 可以编辑的。感谢反馈。
