### ISSUE TITLE
添加针对当前文档进行复习的toolbar按钮

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#17]
在某一文档按下间隔重复快捷键，就可以换出当前文档的闪卡，但是在手机和平板上无法使用快捷键，只能从右上角菜单跳转，我跟官方沟通过，他们表示不想添加多余设计。

**Comment by AvoidantPerDis** [comment]
文档的判定，要不根据当前页签来？

**Comment by IAliceBobI** [comment]
目前的问题是，手机上无法打开页面。没办法弹出闪卡。

**Comment by AvoidantPerDis** [comment]
那要不坐在右键菜单的插件里面？

**Comment by IAliceBobI** [comment]
也不能打开页面。打开页面也打开闪卡都是用的  openTab 功能。得等他重做手机应用才行。手机端，现在渐进阅读插件都无法自动打开分片。

**Comment by AvoidantPerDis** [comment]
OK，那算了

**Comment by AvoidantPerDis** [comment]
没事没事，大佬，你做的插件现在已经很好用了，我还得多谢谢你
