### ISSUE TITLE
移动端闪卡优先级显示bug

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#18]
![Screenshot_2024-02-08-19-21-44-965_org b3log siyuan-edit](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/c3fc65e1-ed46-4602-b1f5-e5ca212e6583)
虽然能从属性里调，但是这样不方便

**Comment by AvoidantPerDis** [comment]
我记得之前版本显示是正常的

**Comment by AvoidantPerDis** [comment]
加了暂停后就奇怪了

**Comment by IAliceBobI** [comment]
@AvoidantPerDis   请关注新版本： https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.16.39

**Comment by AvoidantPerDis** [comment]
哥，你真是神速啊
