### ISSUE TITLE
嵌入块内部以标题块制卡的时候，外部以嵌入块制卡没有优先级属性

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#20]

**Comment by IAliceBobI** [comment]
能录屏看看不？ @AvoidantPerDis

**Comment by AvoidantPerDis** [comment]
[PixPin_2024-03-03_17-20-42.zip](https://github.com/IAliceBobI/sy-tomato-plugin/files/14472334/PixPin_2024-03-03_17-20-42.zip)

**Comment by AvoidantPerDis** [comment]
gif传不了

**Comment by IAliceBobI** [comment]
目前先F5刷新，看嵌入块容器的优先级。如果点击文档内容任何地方，就变成看嵌入块的优先级。

**Comment by AvoidantPerDis** [comment]
抱歉，之前没看到，问题解决了

**Comment by AvoidantPerDis** [comment]
抱歉，之前没看到，问题解决了
