### ISSUE TITLE
闪卡推迟相关功能

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#21]
我发现
* 先正常推迟`xx`天
* 根据距今日期的差输入`-xx`天即可取消推迟
不过用这个办法不知道能不能全文档生效，我看好像是动态生效
但是没发现批量修改方法，我能想到就是用集成编辑环境正则改属性
另外，根据书签数量检查，好像数量多起来后，不能一次性全部暂停

**Comment by IAliceBobI** [comment]
@AvoidantPerDis 右键可以修改文档与子文档。直接设置为0、-1就可以立刻复习。

**Comment by IAliceBobI** [comment]
目前有缓存。你可以重启看新的到期时间。等 https://github.com/siyuan-note/siyuan/issues/10535  通过了，就可以立刻看到新到期时间了。

**Comment by AvoidantPerDis** [comment]
谢谢

**Comment by AvoidantPerDis** [comment]
额，暂停的时间显示能换种方式吗，目前这种影响到原文和嵌入块的显示了

**Comment by AvoidantPerDis** [comment]
这样可行吗
## 利用集成编辑环境实现闪卡暂停

* 搜索custom-riff-decks
* 替换customriffdecks

**Comment by AvoidantPerDis** [comment]
或者能指定全局闪卡文档，就可以跳过暂停的了

**Comment by IAliceBobI** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/3294007/274d800a-d98b-4961-a7ef-82a407b7cc22)

@AvoidantPerDis

**Comment by AvoidantPerDis** [comment]
额不是这个意思，是移动端快速进入闪卡 pc端有间隔重复快捷键

**Comment by IAliceBobI** [comment]
这个不知道。
