### ISSUE TITLE
设置文档下默认优先级和优先级保护

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#22]
https://zhuanlan.zhihu.com/p/364351955?utm_source=ld246.com
这个这个能做吗
>结合 SuperMemo 的渐进阅读，这个优势更加明显：摘抄或挖空产生的卡片，其默认优先级是与原文的优先级有关的。
>优先级保护的值越低，说明有越重要的卡片还没被复习，越高即剩下的卡片不太重要。这样一来，我们便可以参考优先级保护，来决定是否停下 SuperMemo 的复习，切换去做别的学习任务。

**Comment by IAliceBobI** [comment]
思源做统计，统计当前要刷的卡的信息。估计有这个考虑。你可以提提需求。让给出当前要刷的卡的重要程度。

**Comment by AvoidantPerDis** [comment]
现在还是先等重构吧，也不知道啥时候好

**Comment by AvoidantPerDis** [comment]
https://github.com/siyuan-note/siyuan/issues/10438

**Comment by IAliceBobI** [comment]
就按照优先级来吧。目前我改为了严按照优先级来，没有低优先级随机跳跃到高优先级前面的情况。

如果你刷到了低优先级的卡，就可以停止了。

**Comment by AvoidantPerDis** [comment]
ok
