### ISSUE TITLE
「底部反链默认提及数」无法设置为 0 

### ISSUE THREAD

**Issue by TCOTC** [IAliceBobI/sy-tomato-plugin#23]
在这里设置只能大于 0 ：

![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/78434827/180208c4-ccbe-4a8e-b2e1-4f38af6610b6)

在这里可以设为 0 并生效：

![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/78434827/e86006ba-4c03-433f-b5ac-9e28511c6159)

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.19.57

已经修复，谢谢反馈。
