### ISSUE TITLE
「添加书签」功能

### ISSUE THREAD

**Issue by TCOTC** [IAliceBobI/sy-tomato-plugin#24]
之前用「阅读点」来快捷添加书签，但现在的「阅读点」已经不符合我的需求了，所以希望增加一个「添加书签」功能：

- 给内容块添加书签：把文档名作为书签名
- 给文档添加书签：把上级文档名（没有上级文档就用笔记本名）作为书签名

**Comment by IAliceBobI** [comment]
是不想要加入闪卡？

**Comment by TCOTC** [comment]
对的，而且不只是闪卡，「自动删除当前文件内的其他书签，以保持本文件内只有一个书签」也不符合我的需求。我只是单纯地想一键添加书签

**Comment by IAliceBobI** [comment]
我想想，主要是你这功能我也用不上。

**Comment by IAliceBobI** [comment]
> 对的，而且不只是闪卡，「自动删除当前文件内的其他书签，以保持本文件内只有一个书签」也不符合我的需求。我只是单纯地想一键添加书签

加个TODO书签吧，点一下快捷键，加一个。目前在快捷菜单内有清理所有书签的功能。

配合起来，可以方便阅读时来回跳转。

**Comment by IAliceBobI** [comment]
@TCOTC 在文档内打标记来回跳转：ctrl+F1给内容块打小旗书签，ctrl+F2删除文档内所有小旗书签。


和你描述的不太一样。这种场景也是有需要的。

https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.19.87

**Comment by TCOTC** [comment]
新版有这个功能了吗？

**Comment by IAliceBobI** [comment]
> 新版有这个功能了吗？
对

**Comment by TCOTC** [comment]
是放在哪里了？

![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/78434827/0affeaee-1b1b-4b75-a6ed-e53597b1a145)

![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/78434827/81ed3acc-beff-4c78-9033-9795218f8c18)

**Comment by IAliceBobI** [comment]
> 是放在哪里了？
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/316553038-0affeaee-1b1b-4b75-a6ed-e53597b1a145.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjQ2MTEsIm5iZiI6MTcxMTQyNDMxMSwicGF0aCI6Ii83ODQzNDgyNy8zMTY1NTMwMzgtMGFmZmVhZWUtMWIxYi00Yjc1LWE2ZWQtZTUzNTk3YjFhMTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAzMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZmU4YmZjNDZhMzI3NWUyZWRlOWMwZjQ0MmY4NWQ0YTlkODA5MTc3MDNkY2ZkYjc0ZGU5OGUxNTMzNTk5NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ga9Fh0DyKZZP7C7UcCEg_rermGdCJdRFEDFFOlI5520)
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/316553128-81ed3acc-beff-4c78-9033-9795218f8c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjQ2MTEsIm5iZiI6MTcxMTQyNDMxMSwicGF0aCI6Ii83ODQzNDgyNy8zMTY1NTMxMjgtODFlZDNhY2MtYmVmZi00Yzc4LTkwMzMtOTc5NTIxOGY4YzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAzMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTQxMjMzNjc0ZmU3ZjdkZDZjMGI5OWFiMWM3YTAzMGI1NDllZmI4ZTY1Njc1OTBlOTM5ZGI0OWQwYTI2YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RWWv_fpFY92OpOKUciyVs6OWsZ34vQwyVz85L2ptbbE)

快捷菜单里面

**Comment by TCOTC** [comment]
谢谢，找到了。

**Comment by TCOTC** [comment]
现在用 Ctrl+F1 可以给当前块添加书签，可以再用 Ctrl+F1 删除该块的书签吗？

**Comment by IAliceBobI** [comment]
@TCOTC 回头加一下

**Comment by IAliceBobI** [comment]
@TCOTC https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.19.90
