### ISSUE TITLE
「内容提醒」功能是否还有效？

### ISSUE THREAD

**Issue by TCOTC** [IAliceBobI/sy-tomato-plugin#25]
我看了 README ，但用了之后什么也没发生，感觉很奇怪。但又不知道是插件的问题还是我的问题

**Comment by IAliceBobI** [comment]
测试了可以用。中间重启也可以用。*

https://github.com/IAliceBobI/sy-tomato-plugin/assets/3294007/c787849a-cd76-448f-945c-bfe2617b0e8d

**Comment by TCOTC** [comment]
我新建工作空间试了也不行，控制台有报错：

plugin:sy-tomato-plugin:97 Uncaught (in promise) TypeError: Cannot create property '20240321094208-wsib0gc' on string ''
    at TO.addSchedule (plugin:sy-tomato-plugin:97:3088)
    at HTMLButtonElement.o (plugin:sy-tomato-plugin:97:1288)
addSchedule @ plugin:sy-tomato-plugin:97
o @ plugin:sy-tomato-plugin:97

**Comment by IAliceBobI** [comment]
@TCOTC https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.19.72 尝试修复了一下。可以试试。

**Comment by TCOTC** [comment]
OK，能正常使用了
