### ISSUE TITLE
`阻止连续回车断开列表` 功能异常

### ISSUE THREAD

**Issue by TCOTC** [IAliceBobI/sy-tomato-plugin#26]
光标没有跟随新建的列表。

我没找到稳定的复现步骤，具体见 GIF ：

![阻止连续回车断开列表](https://github.com/IAliceBobI/sy-tomato-plugin/assets/78434827/383eca20-69a2-4900-89ac-b5e696dd5b38)

**Comment by IAliceBobI** [comment]
感谢反馈，改天研究一下。
