### ISSUE TITLE
请问有没有计划开发【自定义番茄钟时长】的功能

### ISSUE THREAD

**Issue by zzz51522** [IAliceBobI/sy-tomato-plugin#3]
非常感谢开发者提供这么方便的插件。
有个小小的需求，不知是否可以在下次迭代时考虑进去。

希望可以自定义番茄钟时长，或者提供45min、60min的选项。
因为插件目前最长的番茄钟为25min，个人使用过程中，25min过短，总是打断工作节奏。

希望开发者可以考虑，辛苦

**Comment by IAliceBobI** [comment]
[release](https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.3.50)
