### ISSUE TITLE
希望可以增加邮件提醒功能

### ISSUE THREAD

**Issue by linjie7674** [IAliceBobI/sy-tomato-plugin#30]
目前只能在思源打开的时候才能收到提醒，如果能通过发邮件的方式，就可以随时随地收到提醒了。

**Comment by IAliceBobI** [comment]
说的是设置提醒  ctrl+3 那个功能？

**Comment by linjie7674** [comment]
> 说的是设置提醒 ctrl+3 那个功能？

是的

**Comment by IAliceBobI** [comment]
插件只有你打开编辑器时，才运行的。运行了才能发邮件，不过都运行了，就已经接到通知了。没必要发邮件了。
