### ISSUE TITLE
底部反链 希望除了复制到文档 , 还增加 复制引用/嵌入 到文档

### ISSUE THREAD

**Issue by leeyaunlong** [IAliceBobI/sy-tomato-plugin#31]
底部反链 
- 希望除了复制到文档 , 还增加 复制引用/嵌入 到文档的功能
- 还增加一下 每个反链搞个序号, 因为反链多了后,目前这个显示效果有点看不清,当前看到哪条反链了.

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.20.29
