### ISSUE TITLE
给文档添加全拼、简拼属性 这个怎么使用?

### ISSUE THREAD

**Issue by leeyaunlong** [IAliceBobI/sy-tomato-plugin#32]
给文档添加全拼、简拼属性 这个怎么使用?
enable后, 没有地方激活啊

**Comment by IAliceBobI** [comment]
@leeyaunlong  两个地方可以用。

一个是F3, 需要把官方F3快捷键删除，这个插件F3就生效。      F3可以把选中的内容转为引用，没文件时创建文件。   如果没选中文件，会把光标处的内容按空格拆分后，全转引用。


另一个地方是标签转引用。写好的内容中如果有标签，回车后会把标签转为引用。

**Comment by IAliceBobI** [comment]
只有转引用时，并且创建文件才会加py

如果文件已经存在，只是转引用，不创建文件，则不加py。

**Comment by IAliceBobI** [comment]
不过我打算改为  内容中有  `[[ABC`   这样的情况才会转引用。

**Comment by leeyaunlong** [comment]
> 只有转引用时，并且创建文件才会加py
> 
> 如果文件已经存在，只是转引用，不创建文件，则不加py。

能加个功能吗?
如果选中了文字就把 选中的文字, 和对应的拼音 加入 到 系统属性的 "别名"中.
如果没有选中文字 就把文件名的拼音 加入 到 系统属性的 "别名"中.

**Comment by IAliceBobI** [comment]
后面找个时间看看吧。
