### ISSUE TITLE
底部反链区分隔符

### ISSUE THREAD

**Issue by Foundation-Maker** [IAliceBobI/sy-tomato-plugin#33]
![CleanShot_2024-05-02 _ 15 17 39@2x](https://github.com/IAliceBobI/sy-tomato-plugin/assets/46839690/728954fb-5572-432d-8cc6-e22f634f9382)

文字与底部反链区是否可以增加一个分割符，或着带颜色的空行 来 分割他们。有点看混了。

**Comment by IAliceBobI** [comment]
加了页面的元素更多，会不会更加乱？
第一行是小字，应该可以区分。

**Comment by IAliceBobI** [comment]
> ![CleanShot_2024-05-02 _ 15 17 39@2x](https://private-user-images.githubusercontent.com/46839690/327344910-728954fb-5572-432d-8cc6-e22f634f9382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTU5ODUsIm5iZiI6MTcxNzA1NTY4NSwicGF0aCI6Ii80NjgzOTY5MC8zMjczNDQ5MTAtNzI4OTU0ZmItNTU3Mi00MzJkLThjYzYtZTIyZjYzNGY5MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA3NTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwODc4ZTU2ZGE2Nzc5NjZjZGRhMGNiNWUzNzhhMjBmYzNmYjZlYWMwZTY1ZjAxYmJlMGE5Nzk3NDNiYjUwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RPDj5VF2-f30vZmDHKP1ePVbDyrxVQ-zuuSyVrNSHDI)
> 
> 文字与底部反链区是否可以增加一个分割符，或着带颜色的空行 来 分割他们。有点看混了。

已经加上分隔符。感谢反馈。
