### ISSUE TITLE
想请教怎么实现的如下两个功能

### ISSUE THREAD

**Issue by DionathanJoestar** [IAliceBobI/sy-tomato-plugin#34]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/133741096/d92c8c61-2297-410b-a3c7-656bf9ade7bf)

**Comment by IAliceBobI** [comment]
目前这两个功能被移除了。改天再放进来。

**Comment by IAliceBobI** [comment]
@DionathanJoestar 

不要意思，记错了，没删除，可以在命令面板找到。

![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/3294007/10b1593d-ba5d-4d44-b9a5-77ac26f40e13)
