### ISSUE TITLE
左右分屏的时候，焦点在右文档，但 `全局定位文档` 定位的是左文档

### ISSUE THREAD

**Issue by TCOTC** [IAliceBobI/sy-tomato-plugin#35]

**Comment by IAliceBobI** [comment]
@TCOTC 官方的定位你第一次点的时候有效，第二次点就跑到左边的文档了。

**Comment by IAliceBobI** [comment]
我感觉他们修复了，我这个自动就好。

**Comment by IAliceBobI** [comment]
@TCOTC 我部分修复了。 现在通过顶部topbar的按钮可以定位右边窗口了。alt+1不行。因为点击alt+1的时候会失去焦点，思源默认打开左边的窗口。alt+1需要做更多的工作才行
