### ISSUE TITLE
关于插件菜单的区分

### ISSUE THREAD

**Issue by leeyaunlong** [IAliceBobI/sy-tomato-plugin#37]
你做的两个插件 番茄和渐进阅读功能非常强大,

但现在遇到个问题, 插件菜单中太乱,几十个功能, 以至于经常找不到你这两个插件的子功能(要耗费精力去肉眼识别)
你能不能 对你做的这两个 在 "插件"菜单中 搞个标识? 开头搞个emoji 的番茄 或者后缀 啥的?

![image](https://github.com/IAliceBobI/sy-plugins/assets/19405648/3bb28f45-5151-4288-8dee-b3cea64de404)

**Comment by IAliceBobI** [comment]
done
