### ISSUE TITLE
使用assets 整理功能后，丢失很多资源。

### ISSUE THREAD

**Issue by horizzzonn** [IAliceBobI/sy-tomato-plugin#38]
问题：
丢失的资源中一部分是图片的路径已经换成了新的文件夹路径，但是还是会显示旧的路径丢失（在丢失资源处复制名字可以找到）；
另一部分是图片的路径没有自动更换（复制名字找不到，文档内直接图裂了）。
-
因为我的图片太多，已经回滚历史了，不方便复现，所以描述了一下情况。
-
提议：
能否只选择某些文档来整理此文档下的assets，或者增加其他可以选择部分assets 的方式来整理？因为没整理过的assets 基数太大了，第一次使用这个工具，计算量太大，出错了就要全部回滚。
-
谢谢作者制作的工具。

**Comment by horizzzonn** [comment]
> 后续增加整理某个文档和其子文档的图片。
> 
> 要是着急可以导出部分内容到新的工作空间，在那边整理。
> 
> @horizzzonn

感谢你的回复，很高兴看到要新增这样的功能，非常感谢。
---
我没有尝试过分不同的工作空间，不知道这样还能不能很好地合并到一起。
不过如果这个新功能在不久后会更新，我会等你更新了再整理assets。我先用编辑工具整理一部分，暂时让assets 根目录下稍微少一点好嘞。

**Comment by IAliceBobI** [comment]
@horizzzonn 是有bug的，不是文件太多的问题。bug改好了，就不要加麻烦的功能了，直接一次到位。

**Comment by IAliceBobI** [comment]
移动时候有把路径名字改为小写，所以出现了部分资源丢失的问题。已经修复。
