### ISSUE TITLE
如何设置 反链的刷新功能为 默认不刷新?

### ISSUE THREAD

**Issue by leeyaunlong** [IAliceBobI/sy-tomato-plugin#39]
如何设置 反链的刷新功能为 默认不刷新?
由于页面的引用较多, 整个页面下半部分不停自动刷新. 每次手工关闭刷新太麻烦了, 能否提供选项,默认不刷新?

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v1.0.15

done
