### ISSUE TITLE
底部反链可以编辑但编辑后会重复条数，鼠标悬浮引用就会打开页签

### ISSUE THREAD

**Issue by mozhux** [IAliceBobI/sy-tomato-plugin#4]
作者好，新版插件更新后底部反链有时候可以直接被编辑，但编辑后点击更新sql啥的会变成重复多条数据，而且删除后依然存在这个问题
测试发现，似乎是点一下刷新就会重复一次。
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/46953371/e3bd9a9b-2782-4c68-b412-b10a014d00a3)
第二个问题是反链中的引用只要悬浮就会被自动打开，有点问题，希望是点击打开。
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/46953371/a2e880d6-5f34-4ffc-87e1-dfe012f85a96)

**Comment by IAliceBobI** [comment]
刷新确实会多点内容，如果刷新用f5替代先。


另外，悬浮打开，是指弹出一个悬浮框，还是直接打开一个页签？我这里只是弹出一个悬浮框，这个特性是继承思源的。

**Comment by mozhux** [comment]
> 刷新确实会多点内容，如果刷新先用f5替代。目前我也不太了解里面的机制。
> 
> 另外，悬浮打开，是指弹出一个悬浮框，还是直接打开一个页签？我这里只是弹出一个悬浮框，这个特性是继承思源的。
> 
> 不过弹出的框，我也不看，哈哈。我加个开关，可以替换链接为按钮吧。

就是鼠标放上去，弹窗的同时会自动打开一个页签，两个都处罚了，难道是插件冲突了？

**Comment by IAliceBobI** [comment]
> 作者好，新版插件更新后底部反链有时候可以直接被编辑，但编辑后点击更新sql啥的会变成重复多条数据，而且删除后依然存在这个问题 测试发现，似乎是点一下刷新就会重复一次。 ![image](https://private-user-images.githubusercontent.com/46953371/288931231-e3bd9a9b-2782-4c68-b412-b10a014d00a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjM3NzAsIm5iZiI6MTcwMjAyMzQ3MCwicGF0aCI6Ii80Njk1MzM3MS8yODg5MzEyMzEtZTNiZDlhOWItMjc4Mi00YzY4LWI0MTItYjEwYTAxNGQwMGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4MTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YzIwNzI0Y2YyNmNlNzcyZmMxOTgwNzQwNjNlNWZiMmUwMDdjNGY5ZDc3MTQyZmE2NDcyNmRhY2U0MDVlOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eriLhGCGN4ENWYEU2RYrQ7-V_dHg4_K9D_dt_3i8HeM) 第二个问题是反链中的引用只要悬浮就会被自动打开，有点问题，希望是点击打开。 ![image](https://private-user-images.githubusercontent.com/46953371/288931335-a2e880d6-5f34-4ffc-87e1-dfe012f85a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjM3NzAsIm5iZiI6MTcwMjAyMzQ3MCwicGF0aCI6Ii80Njk1MzM3MS8yODg5MzEzMzUtYTJlODgwZDYtNWYzNC00ZmZjLTg3ZTEtZGZlMDEyZjg1YTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4MTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YzZmYTE2NTJjZTQ2M2UwMjdjZTZmOGRkNzlhYTY1OWRiNmQ4NjJkMWFmMDM1YzMyNDk0ZjIzMmI5MTNiZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ix39y5pVxOKy97o0ogx7GpJ_Ana2vISoZxPneH4NxQE)

编辑后重复的问题修复了。

**Comment by IAliceBobI** [comment]
@mozhux 目前不用js嵌入块了。如果，鼠标悬浮还会打开页签，请再提issue。谢谢。
