### ISSUE TITLE
请问可以整理PDF及PDF笔记，html，文件吗

### ISSUE THREAD

**Issue by lyyjyll** [IAliceBobI/sy-tomato-plugin#40]
请问可以增加其他文件格式的整理功能吗，例如PDF，HTML，PDF笔记，等等

**Comment by IAliceBobI** [comment]
半年前，PDF 我尝试过，改变位置后，无法正常使用。你可以尝试手动改位置试试，不行的话给思源提个需求。如果移动位置后可用。就有了整理的基础。  @lyyjyll

**Comment by lyyjyll** [comment]
谢谢您的及时回复，我试试看。 @IAliceBobI
