### ISSUE TITLE
适配blocktree storage重构后新接口

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#41]
https://github.com/siyuan-note/siyuan/issues/11773#issuecomment-2182576505

**Comment by IAliceBobI** [comment]
#11786

**Comment by AvoidantPerDis** [comment]
请问适配了新接口了吗

**Comment by IAliceBobI** [comment]
直接盲写了。等发布了再测试。

**Comment by IAliceBobI** [comment]
目前是，如果发现3.1就使用新接口。但没测试过。

**Comment by AvoidantPerDis** [comment]
ok，我到时候帮忙测试

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/b996dd1b-e384-4c32-b0ef-94ef66101bae)
dev7应该是还没用上

**Comment by IAliceBobI** [comment]
完整的版本号是什么？
估计后面有非数字，被判断为0

**Comment by AvoidantPerDis** [comment]
https://github.com/siyuan-note/siyuan/releases/tag/v3.1.0-dev7
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/84417035-2d74-4d85-9cb7-b6a41c40ebd3)
还没到3.1.0

**Comment by IAliceBobI** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/3294007/14e9772e-2e46-443f-8b4c-c42f9e8d6325)

你那边应该是true。你的版本相当于  3.1

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/a07a43e8-8140-412c-a200-93bce56dfdae)
好像没有消息

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/908a459f-646d-446e-b6cf-c9ea209d93c1)
而且xbbj新版本只有2张闪卡都变得很慢

**Comment by IAliceBobI** [comment]
得在控制台输入自己  tomato_zZmqus5PtYRi.utils.versionGreaterEqual('3.1')

  才行。

**Comment by IAliceBobI** [comment]
我看就是调用的接口没返回。你可点击那些待处理的接口，你看看传入的参数是什么。如果速度太慢，可以给官方看看。

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/d7e7e4f8-63dd-4249-9a87-8cf23af8e56c)
dev7是false诶

**Comment by IAliceBobI** [comment]
siyuan.config.system.kernelVersion


![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/3294007/e7bb4029-a3ea-4420-bf1b-5c29624ee466)


你看看这个呢？

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/4c090254-eba6-49ca-b62f-e2b2eabbd32c)

**Comment by AvoidantPerDis** [comment]
好像dev是不会换版本号的

**Comment by IAliceBobI** [comment]
那就没办法搞了。可以问问官方是不是可以换。按道理应该换的。

**Comment by AvoidantPerDis** [comment]
dev不换版本号也合理，毕竟有时候会跳版本号，我先用老版吧

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/b8adb6f9-0c1c-4182-92c2-0c8ca6fe7504)
感觉速度还是不对

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/1ccd4706-e3a8-436e-8613-ed1997331fab)
77张卡

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/4331ccf6-3613-4f36-8bf2-4f2bc2af96c0)

**Comment by IAliceBobI** [comment]
@AvoidantPerDis 你安装时间倒序。看看哪个调用最多。我这里看是  getRiffDueCards 最多。   也就读取改复习卡片的速度太慢。

**Comment by AvoidantPerDis** [comment]
看来是思源本体的问题

**Comment by IAliceBobI** [comment]
不仅是 getRiffDueCards ，看你图中，读取面包屑的调用也慢。得官方针对优化了。

**Comment by AvoidantPerDis** [comment]
> 不仅是 getRiffDueCards ，看你图中，读取面包屑的调用也慢。得官方针对优化了。

那个好像是层级导航插件的功能

**Comment by IAliceBobI** [comment]
我这里32张卡。

![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/3294007/8c3affc9-0b31-468d-954f-fc47597a3a81)

**Comment by IAliceBobI** [comment]
我这里读取面包屑也不慢。

就是读取复习卡慢。

这个得思源那边优化。
