### ISSUE TITLE
闪卡优先级右侧的滑块提供隐藏选项

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-tomato-plugin#42]
我闪卡优先级都是49-53五级，平时用不上滑块，，有数据库标识或是超级块的情况下回阻挡其他内容

**Comment by AvoidantPerDis** [comment]
另外 暂停按钮我也不常用，也希望可以隐藏，或者css也行

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/2f25ecce-606c-48a0-90fb-4f464cc257a9)
对了，新版调完一次优先级工具条就会隐藏，不方便连续调解，是特性还是bug呀？

**Comment by IAliceBobI** [comment]
应该是没刷新的问题。不知道是思源改了，还是我改了。

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/cdc54b84-84fe-4c20-b75b-4af93f07dfe0)
好像有新bug了

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/IAliceBobI/sy-tomato-plugin/assets/154863885/00a930d7-60af-4434-80d7-fc50e48801b7)

**Comment by AvoidantPerDis** [comment]
重启思源又好了

**Comment by IAliceBobI** [comment]
@AvoidantPerDis 发布了 v1.0.31 ，应该好了。我这边测试没问题。一会儿请帮忙试试。

**Comment by AvoidantPerDis** [comment]
好了，辛苦了
