### ISSUE TITLE
请问拍照闪念能否加入录音和录像功能？

### ISSUE THREAD

**Issue by pisceswb** [IAliceBobI/sy-tomato-plugin#43]
请问能否在移动端增加录音和录像功能，这样可以使用手机拍照、录像、录音插入到思源笔记中，完善一下记录功能。
另外，为了移动端快速启用，能否能单独做一个插件的快捷方式图标，点击后能直接使用拍照、录音、录像功能收集信息后，自动插入思源笔记中。
谢谢！

**Comment by IAliceBobI** [comment]
直接录音录像不好搞。插入音频视频还是可以的。
