### ISSUE TITLE
能不能考虑支持dify的知识库调用呢

### ISSUE THREAD

**Issue by Pan06da** [IAliceBobI/sy-tomato-plugin#44]

**Comment by IAliceBobI** [comment]
标记一下，https://cloud.dify.ai/datasets， 后面看时间吧。这个是否需要梯子？

**Comment by Pan06da** [comment]
是基于本地的，可以离线部署 dify 在本地。模型用 ollama 加载






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月12日 22:48 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [IAliceBobI/sy-tomato-plugin] 能不能考虑支持dify的知识库调用呢 (Issue #44) |

标记一下，https://cloud.dify.ai/datasets， 后面看时间吧。这个是否需要梯子？

**Comment by IAliceBobI** [comment]
[这个](https://docs.dify.ai/getting-started/install-self-hosted)吗，大模型，我电脑跑起来有点吃力了。小一点的模型效果有不好。
