### ISSUE TITLE
反链的按照创建时间排序，能否精确到块的创建时间呢？

### ISSUE THREAD

**Issue by Tisamn** [IAliceBobI/sy-tomato-plugin#47]
目前是文档的创建时间

**Comment by IAliceBobI** [comment]
已经更新了，可以试一试看。
________________________________
From: ***@***.*** ***@***.***> on behalf of Tisamn ***@***.***>
Sent: Sunday, September 29, 2024 9:37 PM
To: IAliceBobI/sy-tomato-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [IAliceBobI/sy-tomato-plugin] 反链的按照创建时间排序，能否精确到块的创建时间呢？ (Issue #47)


目前是文档的创建时间

―
