### ISSUE TITLE
版本更新后，块引的悬浮窗不再显示反链

### ISSUE THREAD

**Issue by Tisamn** [IAliceBobI/sy-tomato-plugin#49]
![Quicker_20241002_114245](https://github.com/user-attachments/assets/51c0f602-2320-4220-841d-d611f11d861f)
![Quicker_20241002_114331](https://github.com/user-attachments/assets/bcfac3af-ee00-4db5-9d8a-e21e00482cc6)
但这个功能是刚需~

**Comment by IAliceBobI** [comment]
加了一个选项。
