### ISSUE TITLE
底部反链建议不体现在导出中

### ISSUE THREAD

**Issue by mozhux** [IAliceBobI/sy-tomato-plugin#5]
如题，底部反链在导出时会显示反链2字，建议不体现。

**Comment by IAliceBobI** [comment]
哈哈，我不使用导出。本来是想着有个标题，能在大纲里面快速定位的。我加个开关吧，默认关闭。后面看看有什么方法既能大纲定位，又不加入标题。

**Comment by IAliceBobI** [comment]
@mozhux 目前已经改了整个策略，不再使用嵌入块的方式。所以也不会体现到导出中了。
