### ISSUE TITLE
获取今日复习的闪卡时，能否把今天内要复习的闪卡都过滤出来

### ISSUE THREAD

**Issue by 397334469** [IAliceBobI/sy-tomato-plugin#51]
一天内打开思源的时间不多，而闪卡复习却分散在不同的时间断内，能否点击复习时，把今天内应该复习的闪卡都过滤出来复习呢，1分钟之后，5分钟之后，对于我们来说并没有什么不同。

**Comment by IAliceBobI** [comment]
看到多少就复习多少，看不到的明天再复习，无所谓的。


算起来是一样的效果。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月12日(周六) 晚上7:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [IAliceBobI/sy-tomato-plugin] 获取今日复习的闪卡时，能否把今天内要复习的闪卡都过滤出来 (Issue #51)




 
一天内打开思源的时间不多，而闪卡复习却分散在不同的时间断内，能否点击复习时，把今天内应该复习的闪卡都过滤出来复习呢，1分钟之后，5分钟之后，对于我们来说并没有什么不同。
