### ISSUE TITLE
支持传递双链显示*

### ISSUE THREAD

**Issue by chenshinshi** [IAliceBobI/sy-tomato-plugin#52]
现在通过快捷键传递双链后，新建的双链是原关联块的全部文字，我每次都需要手动将链接文字改成*。
![image](https://github.com/user-attachments/assets/290a144e-6ab6-453f-80bf-879a5dddc35e)

不知道可否支持一个开关直接把传递过去的双链的文字改成*？
![image](https://github.com/user-attachments/assets/6449a584-5313-45a2-92f4-3961e85691af)

**Comment by IAliceBobI** [comment]
![image](https://github.com/user-attachments/assets/092e4b02-a50a-48bb-903d-772d4fc26687)


新版本把这个选项关掉就行。

**Comment by IAliceBobI** [comment]
v2.4.44
