### ISSUE TITLE
闪卡显示有3张，但点击之后，提示说没有了

### ISSUE THREAD

**Issue by 397334469** [IAliceBobI/sy-tomato-plugin#53]
![image](https://github.com/user-attachments/assets/83bd5848-29ee-4f49-9bc8-1de4a54d5656)

**Comment by IAliceBobI** [comment]
20秒钟更新一次。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月14日(周一) 上午9:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [IAliceBobI/sy-tomato-plugin] 闪卡显示有3张，但点击之后，提示说没有了 (Issue #53)




 
image.png (view on web)

**Comment by 397334469** [comment]
刚刚有超过20秒，还是会显示。
是不是这个查询是把今天内的要复习的都过滤出来？再过了几分钟之后，有出来3个闪卡，把他们复习完成之后，就正常了。

**Comment by IAliceBobI** [comment]
不会的，就是用的是思源提供的接口，跟他们的功能是一致的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月14日(周一) 上午10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IAliceBobI/sy-tomato-plugin] 闪卡显示有3张，但点击之后，提示说没有了 (Issue #53)




 
刚刚有超过20秒，还是会显示。
 是不是这个查询是把今天内的要复习的都过滤出来？再过了几分钟之后，有出来3个闪卡，把他们复习完成之后，就正常了。
