### ISSUE TITLE
复制到dailynote显示原文路径功能对部分块类型失效。

### ISSUE THREAD

**Issue by youngerruan** [IAliceBobI/sy-tomato-plugin#55]
我打开了复制到dailynote选项，开启了复制的内容显示原文的路径选项。

对于普通的文本块来说，该功能可以正常使用

对于无序列表来说，复制到dailynote后，自定义属性有对应的选项，但是属性值是空的。所以显示不了路径，但是块上面显示路径的位置还是空出来了。

**Comment by IAliceBobI** [comment]
v2.4.45    试是这个版本。

**Comment by youngerruan** [comment]
完美解决了，感谢您！另外反馈一个小bug，就是双屏的时候，鼠标焦点在副屏，然后快捷键呼出拍照闪念，会全屏展开。鼠标焦点在主屏幕没有这个问题。（不影响使用）
