### ISSUE TITLE
拍照闪念,选择文本后,“引用”,链接,粗体,这些功能没有,能否添加上工具栏？

### ISSUE THREAD

**Issue by uulaile** [IAliceBobI/sy-tomato-plugin#57]

**Comment by IAliceBobI** [comment]
这个功能快速记录想法都是纯文字的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月19日(周六) 晚上9:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [IAliceBobI/sy-tomato-plugin] 拍照闪念,选择文本后,“引用”,链接,粗体,这些功能没有,能否添加上工具栏？ (Issue #57)
