### ISSUE TITLE
传递型双链在底部反链中显示错误

### ISSUE THREAD

**Issue by Tisamn** [IAliceBobI/sy-tomato-plugin#58]
![daa43c9275d3a77a0f9d355425fa9e25](https://github.com/user-attachments/assets/840e4402-d705-4d60-ab14-f051418ea921)
![3bf4ccc28a298c60786cbddd57a3728e](https://github.com/user-attachments/assets/56b2c564-5b31-4081-b5d5-34db4d261600)
思源更新新版本后，类似于图片1的传递型双链，在番茄工具箱的文档底部反链中不显示，但是在思源自带的反链中显示正常，如下图所示
![97dae6f55fbec7a24107fc1d43df32d1](https://github.com/user-attachments/assets/23426064-7546-438c-9ac6-e3a40763c5bf)

**Comment by IAliceBobI** [comment]
v2.4.54  试试这个版本。

**Comment by Tisamn** [comment]
> v2.4.54 试试这个版本。

已解决，感谢佬！

**Comment by Tisamn** [comment]
> v2.4.54 试试这个版本。
![tmp941D](https://github.com/user-attachments/assets/9f988bd3-4f83-42e5-a00f-a06931f47d5f)
佬，才注意到这个问题：底部反链中部分反链不显示面包屑，传递型双链都不显示面包屑

**Comment by IAliceBobI** [comment]
v2.4.55   这个。

 官方的反链现在挺好的。非常简洁。

**Comment by Tisamn** [comment]
> v2.4.55 这个。
> 
> 官方的反链现在挺好的。非常简洁。

emmm，佬说真的您这功能比官方自带的丰富度太高了，官方实现不了需求，而且去官方提方案感觉目前也难以受到关注~
您是不想做下去了嘛，番茄工具的功能真的好用，不希望它离开~
其实您可以像Kmind插件一样，实行买99元断制收费，我肯定会支持的，而且目前下载榜第一，收益应该也很可观

**Comment by IAliceBobI** [comment]
多谢建议。暂时还没想好好的方案。
