### ISSUE TITLE
可否独立插入*和带文本插入为两组快捷键

### ISSUE THREAD

**Issue by chenshinshi** [IAliceBobI/sy-tomato-plugin#59]
感恩老大支持了插入\*链接，非常好用！
最近自己啃英文原著时又发现了新的使用场景，有时需要将单词关联到原著，这时其实用不到把两边都变成\*，而是直接插入带文本的双链更合适。
但实现这个操作就需要在番茄设置中来回开关带文本选项，所以就想到了能否直接把这两种各自做成快捷键。
能实现的话真的万分感谢！

**Comment by IAliceBobI** [comment]
最近有点忙，得过段时间。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 上午9:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [IAliceBobI/sy-tomato-plugin] 可否独立插入*和带文本插入为两组快捷键 (Issue #59)




 
感恩老大支持了插入链接，非常好用！
 最近自己啃英文原著时又发现了新的使用场景，有时需要将单词关联到原著，这时其实用不到把两边都变成，而是直接插入带文本的双链更合适。
 但实现这个操作就需要在番茄设置中来回开关带文本选项，所以就想到了能否直接把这两种各自做成快捷键。
 能实现的话真的万分感谢！

**Comment by IAliceBobI** [comment]
@chenshinshi 你这个说的是哪个功能呢？   是那个摘录单词的功能吗？

**Comment by IAliceBobI** [comment]
还是那个双向链接的功能？

**Comment by chenshinshi** [comment]
就是用快捷键自动发送*号往返链那个！
现在可以选择发送*号往返链，本块的引用也变为*。
或者两边都是原文字。
我希望可以支持发送*号往返连但本块的引用不会变为*，这样原块（用来放单词的原著出处）的文字不会被修改。
然后可以独立为不同的快捷键。

0x01 ***@***.***> 於 2024年10月25日 週五 下午2:25寫道：

**Comment by IAliceBobI** [comment]
按照你说的情况，不是排列组合有四种吗

**Comment by IAliceBobI** [comment]
试试新版本

**Comment by chenshinshi** [comment]
看到了，新版本是变为只支持不修改原引用但发送一个*的往返链了吗？

**Comment by chenshinshi** [comment]
![image](https://github.com/user-attachments/assets/5081dba4-9805-42d0-80c1-fbc795a655cf)
这是我这边的快捷键页面，好像还没有看到不同的快捷键

**Comment by IAliceBobI** [comment]
> 看到了，新版本是变为只支持不修改原引用但发送一个*的往返链了吗？

对，先暂时这么弄吧

**Comment by IAliceBobI** [comment]
点击链接加入腾讯频道【思源插件】：https://pd.qq.com/s/2fh7nh7gz

后续在这里讨论吧
