### ISSUE TITLE
传递双链会令块焦点消失，光标跳转至块开头

### ISSUE THREAD

**Issue by chenshinshi** [IAliceBobI/sy-tomato-plugin#6]
https://github.com/IAliceBobI/sy-tomato-plugin/assets/125173405/e479cdee-557b-486e-ab8c-414266f3eed2

无论是使用快捷键还是通过菜单传递双链，块都会失去焦点（视频中焦点块有打字机模式的特殊样式可以看到），如果是快捷键的话，光标还会留在块中但是跳转到了开头，不会从原来的位置继续输入，这样还是会比较打断编辑的。（找了两个人测试都是这样）希望作者有空可以修复下，作者辛苦了！

**Comment by IAliceBobI** [comment]
@chenshinshi 您好，确实有这问题。感谢反馈。我之前是写完再用的。没测写一半就用的情况。我会尽快修复。

**Comment by IAliceBobI** [comment]
@chenshinshi 目前尽量不跳，要跳也是跳到末尾。如果有问题请再打开issue。谢谢!
