### ISSUE TITLE
模糊转换@@@ 的方式可否加回来

### ISSUE THREAD

**Issue by xiaoheitan521** [IAliceBobI/sy-tomato-plugin#60]
感谢大佬这块的再优化，但是我感觉相较于现在 之前的方式可能更通用一点
我在手机上面用@@@ 创建模糊转换更方便一点

**Comment by IAliceBobI** [comment]
等过段时间吧。感谢反馈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [IAliceBobI/sy-tomato-plugin] 模糊转换@@@ 的方式可否加回来 (Issue #60)




 
感谢大佬这块的再优化，但是我感觉相较于现在 之前的方式可能更通用一点
 我在手机上面用@@@ 创建模糊转换更方便一点

**Comment by IAliceBobI** [comment]
@@@ 那个容易出来，你不想用的。  不过可以把匹配到的都列出来。  都列在同一行上，全部选中，也算是一种改进。

**Comment by IAliceBobI** [comment]
看看新版本

**Comment by xiaoheitan521** [comment]
> 看看新版本
哦豁，感谢老大，鞠躬🙇‍♀️(੭˙ᗜ˙)੭
