### ISSUE TITLE
跳过的闪卡，到期后页面不会刷新，除非打开配置里的闪卡优先级

### ISSUE THREAD

**Issue by hongdongjie** [IAliceBobI/sy-tomato-plugin#61]
![J_9SO9MW5J2B7RB8E_{N4CF](https://github.com/user-attachments/assets/0824057b-6c70-4015-9cb0-3039ecfcd572)

**Comment by hongdongjie** [comment]
suspended card这个书签也不会刷新

**Comment by hongdongjie** [comment]
我是在闪卡复习时设置的闪卡推迟

**Comment by IAliceBobI** [comment]
打开闪卡优先级了之后就会自动刷新吗

**Comment by hongdongjie** [comment]
> 打开闪卡优先级了之后就会自动刷新吗
是的，但不是打开设置之后，所有到期的闪卡就都刷新，只有页面有打开的才会。如果没有打开，还是会有日期、书签、字迹变淡的效果。
![image](https://github.com/user-attachments/assets/e9764003-5dc3-49b4-b627-99f769aa976a)

**Comment by IAliceBobI** [comment]
我的设计上就是这样。在你去看他的时候，他才会改掉。如果要做成，不看也会改的话，那只能说定时去检查，然后更新了。相当于不断的去定时去刷这些闪卡了。虽然说他不改掉，但是他时间到了，你还是能够去刷卡的。

**Comment by hongdongjie** [comment]
这个设计挺好的，一点问题都没有。不过闪卡优先级的ui在闪卡较多时，有点影响阅读体验，即使隐藏了优先级滑动块和闪卡暂停按钮。不知道以后会不会改成：在设置中关闭闪卡优先级选项，在闪卡复习界面设置推迟复习，然后页面也能刷新？

**Comment by IAliceBobI** [comment]
v2.4.61

看看新版本

**Comment by hongdongjie** [comment]
大佬好强٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ
