### ISSUE TITLE
内容提醒功能增加定期循环提醒功能

### ISSUE THREAD

**Issue by 5kyfkr** [IAliceBobI/sy-tomato-plugin#62]
如题，希望能给内容提醒功能设置定期循环提醒，可以设置指定日期定期几天后重新提醒，方便管理定期重复事项

**Comment by IAliceBobI** [comment]
这个功能实现的比较弱.   目前有好多插件都可以替代。  不知道这个功能还有啥优点。 

我目前主要是双击快捷键，用来复制块 id。 同时控制台也打印出来页面的元素，方便开发用。至于定时功能，我都不用了。

**Comment by 5kyfkr** [comment]
有哪些插件支持块定时提醒？我好像没印象，我主要是用于管理如续费提醒，写周报之类的任务，要加个提醒

**Comment by IAliceBobI** [comment]
有 '日程'    管理的都有吧

**Comment by 5kyfkr** [comment]
> 有 '日程' 管理的都有吧

看了思源里就“日程管理”这插件有这功能，但是这插件没有全屏提醒，只能显示在插件内置的日历列表里，提醒不太够

**Comment by 5kyfkr** [comment]
https://ld246.com/article/1730734930259
看这帖子里也有人需要重复提醒

**Comment by IAliceBobI** [comment]
过段时间再升级一下

**Comment by 5kyfkr** [comment]
https://ld246.com/article/1730866503104# 这里也有两个回复需要重复提醒，这个需求绝对是刚需的

**Comment by IAliceBobI** [comment]
点击链接加入腾讯频道【思源插件】：https://pd.qq.com/s/2fh7nh7gz

后续在这里讨论吧
