### ISSUE TITLE
【BUG】双向链接中的 切换 超链接/块引 无论开关都是超链接

### ISSUE THREAD

**Issue by SaXz2** [IAliceBobI/sy-tomato-plugin#63]
如标题所说
![Clip_2024-11-06_12-34-22](https://github.com/user-attachments/assets/15bc5314-62f0-4d04-956a-da460ab68c6d)
无论开启还是关闭都是超链接效果

**Comment by IAliceBobI** [comment]
目前只对 `alt+/` 这个快捷键的功能有效

**Comment by IAliceBobI** [comment]
你用的是哪个功能

**Comment by SaXz2** [comment]
我用的 
![Clip_2024-11-06_13-34-56](https://github.com/user-attachments/assets/02855d42-1a1f-4bea-ba15-ab5cba7ae4b0)
Alt+/不会用...

**Comment by ioypl** [comment]
> 你用的是哪个功能

alt+/，怎么用，我也是不会用。

**Comment by IAliceBobI** [comment]
![image](https://github.com/user-attachments/assets/6c0b0334-09ee-4582-a9a6-2a3b6ebb804b)

在第二行用  alt+/ 第一行就会出现一个*

**Comment by ioypl** [comment]
> ![image](https://private-user-images.githubusercontent.com/3294007/383456658-6c0b0334-09ee-4582-a9a6-2a3b6ebb804b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODQ5MDAsIm5iZiI6MTczMDg4NDYwMCwicGF0aCI6Ii8zMjk0MDA3LzM4MzQ1NjY1OC02YzBiMDMzNC0wOWVlLTQ1ODItYTlhNi0yYTNiNmViYjgwNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDZUMDkxNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTVlOTI4YjBiMjkwNmM5YjA5MGFiMjdiOTdkODBmYmI1YzcyZTQ5OGQ0YjI1YWIzOTFjZDBjMzU0NGUwYzdkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._I8oSXh_BacwGAciYiaifUA2BfYHjkL1cQqxLfxfZZM)
> 
> 在第二行用 alt+/ 第一行就会出现一个*

完全没反应，右上角没有任何提示，不知是不是哪里设置得不对

**Comment by IAliceBobI** [comment]
@ioypl 看一下快捷键的设置.  看看有没有冲突. 如果没有冲突，你可以先把快捷键删掉. 然后再手动设置一次快捷键.      思源这里有bug， 虽然你看到是这个快捷键，但是不一定能用的起来。  所以要重新手动设置一次。

**Comment by ioypl** [comment]
> @ioypl 看一下快捷键的设置. 看看有没有冲突. 如果没有冲突，你可以先把快捷键删掉. 然后再手动设置一次快捷键. 思源这里有bug， 虽然你看到是这个快捷键，但是不一定能用的起来。 所以要重新手动设置一次。

不行，我关闭了其他所有插件，然后重新设置快捷键，退出重启，用右键菜单使用双链，都还是不行

**Comment by IAliceBobI** [comment]
改成别的快捷键呢

**Comment by IAliceBobI** [comment]
我刚用过是正常的

**Comment by IAliceBobI** [comment]
点击链接加入腾讯频道【思源插件】：https://pd.qq.com/s/2fh7nh7gz

后续在这里讨论吧

**Comment by IAliceBobI** [comment]
v2.5.1 

新的版本起作用
