### ISSUE TITLE
最新版本，鼠标移动到文档页面，页面会出现闪卡颜色的框

### ISSUE THREAD

**Issue by TangQi001** [IAliceBobI/sy-tomato-plugin#64]
![image](https://github.com/user-attachments/assets/22d7c692-f6c3-4e46-88de-709dbc6af88a)

**Comment by IAliceBobI** [comment]
后面我把这个黄色的框去掉

**Comment by IAliceBobI** [comment]
本来是想显示给闪卡内容块的      没想到加入闪卡的文档也显示了

**Comment by IAliceBobI** [comment]
点击链接加入腾讯频道【思源插件】：https://pd.qq.com/s/2fh7nh7gz

后续在这里讨论吧
