### ISSUE TITLE
双链传递似乎不识别有叠加样式的引用

### ISSUE THREAD

**Issue by chenshinshi** [IAliceBobI/sy-tomato-plugin#7]
https://github.com/IAliceBobI/sy-tomato-plugin/assets/125173405/f47d69ac-5d65-439d-98ee-98008870f86e

因为叠加样式后的引用的data-type就不是单纯的block-ref了，可能是mark blockref或者b blockref之类，我试了下加粗、标记、上标都无法识别，只有单纯的引用可以识别。
另外发现，如果是先创建普通引用，再为引用添加样式，可以识别。他们的data-type是block-ref在最前面（如block-ref strong）
如果是已有样式，再添加引用，就不可以识别。block-ref在后面（strong block-ref）
所以我怀疑应该是对block-ref的解析代码有问题，无法识别后一种情况。

**Comment by IAliceBobI** [comment]
@chenshinshi 感谢反馈。我检查一下。

**Comment by IAliceBobI** [comment]
@chenshinshi 之前通过markdown分析，无法查到带外观的链接。目前直接分析页面标签，已经修复。谢谢！
