### ISSUE TITLE
重新加载界面出现的问题

### ISSUE THREAD

**Issue by TCOTC** [IAliceBobI/sy-tomato-plugin#8]
1. 在关闭一些页签后，启用或禁用某项设置，被关闭的页签会重新打开
2. 在打开一些页签后，启用或禁用某项设置，被打开的页签会关闭

链滴：[重新加载界面出现的问题](https://ld246.com/article/1702408791267?r=a2930610542)

**Comment by IAliceBobI** [comment]
@TCOTC 感谢反馈。我想办法解决一下。其实开发的过程中我也发现了，之前也没想到好办法。但你这么一说，我看了思源的添加表情功能，发现他们会先保存一下布局再刷新。我也想办法模仿一下他。再次感谢反馈。

**Comment by IAliceBobI** [comment]
@TCOTC  [应该是好使了。](https://ld246.com/article/1702408791267)
