### ISSUE TITLE
移动到daily note 能不能改成指定的笔记本下面

### ISSUE THREAD

**Issue by uulaile** [IAliceBobI/sy-tomato-plugin#9]

**Comment by IAliceBobI** [comment]
@uulaile 感谢反馈。我记录一下。后续开发。加个配置吧后续。另外有个今日笔记的插件也有类似功能，可以使用。

**Comment by uulaile** [comment]
thank you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月29日(星期五) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IAliceBobI/sy-tomato-plugin] 移动到daily note 能不能改成指定的笔记本下面 (Issue #9)





 
@uulaile 感谢反馈。我记录一下。后续开发。加个配置吧后续。另外有个今日笔记的插件也有类似功能，可以使用。

**Comment by IAliceBobI** [comment]
@uulaile 您好，默认笔记本的配置功能已经加上，欢迎使用。再次感谢您的反馈！

**Comment by uulaile** [comment]
收到&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月30日(星期六) 凌晨0:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IAliceBobI/sy-tomato-plugin] 移动到daily note 能不能改成指定的笔记本下面 (Issue #9)





 
@uulaile 您好，默认笔记本的配置功能已经加上，欢迎使用。再次感谢您的反馈！
